# Generated by Django 2.1.4 on 2019-01-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('post_image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('description', models.TextField(default='This is the description...', max_length=100)),
            ],
        ),
    ]
