# Generated by Django 2.1.4 on 2019-01-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_auto_20190126_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
