# Generated by Django 2.1.4 on 2019-01-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_remove_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
