# Generated by Django 2.1.4 on 2019-01-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_auto_20190127_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetails',
            name='blog',
        ),
        migrations.DeleteModel(
            name='BlogDetails',
        ),
    ]
