# Generated by Django 2.1.4 on 2019-01-27 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0007_blogstuff_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogstuff',
            name='date_published',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
