# Generated by Django 2.1.4 on 2019-02-02 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0008_blogstuff_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogstuff',
            name='date_published',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
